let a = 'hello';
console.log(a);
let b = 'owu';
console.log(b);
let c = 'com';
console.log(c);
let d = 'ua';
console.log(d);
let e = 1;
console.log(e);
let f = 10;
console.log(f);
let g = -999;
console.log(g);
let h = 123;
console.log(h);
let i = 3.14;
console.log(i);
let y = 2.7;
console.log(y);
let x = 16;
console.log(x);
let q = true;
console.log(q);
let w = false;
console.log(w);
